name: ikonfetemobile
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_localizations:
    sdk: flutter
  http:
  uuid:
  flutter_webview_plugin: ^0.2.1+2
  shared_preferences: ^0.4.2
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  flutter_facebook_login:
  flutter_twitter_login:
  flutter_advanced_networkimage:
  photo_view:
  palette_generator:
  residemenu:
  flutter_swiper:
  rxdart:
  progress_indicators: ^0.1.2
  fluro:
  image:
  image_picker:
    git:
      url: git://github.com/tomialagbe/plugins
      path: packages/image_picker
  flutter_svg:
  transparent_image:
  cached_network_image:


dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation:


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/splash_background.png
    - assets/images/Ikonfete_logo_white.png
    - assets/images/onboard_background1.png
    - assets/images/onboard_background2.png
    - assets/images/onboard_background3.png
    - assets/images/onboard_background4.png
    - assets/images/alert.svg
    - assets/images/dark_grunge_bk.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: Themify
      fonts:
        - asset: assets/fonts/themify.ttf
    - family: FontAwesome5
      fonts:
        - asset: assets/fonts/fa-regular-400.ttf
    - family: FontAwesome5Solid
      fonts:
        - asset: assets/fonts/fa-solid-900.ttf
    - family: FontAwesome5Brands
      fonts:
        - asset: assets/fonts/fa-brands-400.ttf
    - family: LineAwesome
      fonts:
        - asset: assets/fonts/line-awesome.ttf
    - family: Bebas
      fonts:
        - asset: assets/fonts/bebas.ttf
    - family: SanFranciscoDisplay
      fonts:
        - asset: assets/fonts/sanfranciscodisplay-medium.ttf
        - asset: assets/fonts/sanfranciscodisplay-semibold.ttf
          weight: 500
        - asset: assets/fonts/sanfranciscodisplay-bold.ttf
          weight: 900
    - family: mermaid
      fonts:
        - asset: assets/fonts/Mermaid1001.ttf
    - family: bebas-neue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf